//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_HD
    {
        public string SoHD { get; set; }
        public string MASP { get; set; }
        public int SL { get; set; }
    
        public virtual Hoadon Hoadon { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
